### ISSUE TITLE
Circle CI

### ISSUE THREAD

**Issue by CSheesley** [CSheesley/koroibos#3]
**Create a new project in Circle CI - link this repo**
Follow this link and add project: https://circleci.com/add-projects/gh/CSheesley 

**Add Circle CI Badge to README**
```
In Circle CI go to the projects settings -> Notifications -> Status Badges.
Copy that block of code and place inside of the README
```

**Configure Circle CI**
Refer to this old PR if needed: https://github.com/CSheesley/ccs_cross_poll_backend/pull/2

Added Database information to config.yml :
```
version: 2
jobs:
  build:
    working_directory: ~/ccs_cross_poll_backend
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: koroibos
      - image: postgres:9.5
        environment:
          POSTGRES_USER: koroibos
          POSTGRES_DB: koroibos_test
          POSTGRES_PASSWORD: ""
```
Although we have no models yet, we needed to run a migration to create a schema in order for CI to run.
Added `gem rspec_junit_formatter` to Gemfile - (for formatting test results that CI checks).
Fixed Bundler issue by adding this run command in config.yml :
```
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v '2.0.2'
```
Added a Workflow section to the config.yml :
```
workflows:
build_and_test:
  jobs:
    - build
    - test
```
Enables Status Checks on PR's, in Github.
