### ISSUE TITLE
Circle CI Setup

### ISSUE THREAD

**Issue by CSheesley** [CSheesley/koroibos#4]
**Add new Project to Circle CI**

**Add Badge to README**

**Configure Circle CI**
Added Database information to config.yml :
```
version: 2
jobs:
  build:
    working_directory: ~/ccs_cross_poll_backend
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: ccs_cross_poll_backend
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ccs_cross_poll_backend
          POSTGRES_DB: ccs_cross_poll_backend_test
          POSTGRES_PASSWORD: ""
```
Although we have no models yet, we needed to run a migration to create a schema in order for CI to run.
Added gem rspec_junit_formatter to Gemfile - (for formatting test results that CI checks).
Fixed Bundler issue by adding this run command in config.yml :
```
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v '2.0.1'
```
Added a Workflow section to the config.yml :
```
workflows:
build_and_test:
  jobs:
    - build
    - test
```
Enables Status Checks on PR's, in Github.
